### ISSUE TITLE
.cabal file: git:// protocol no longer supported

### ISSUE THREAD

**Issue by andreasabel** [haskell-rewriting/union-find-array#6]
https://github.com/haskell-rewriting/union-find-array/blob/ed0e00349192240773dd397dec64b0d730efbd8a/union-find-array.cabal#L22
This URI is no longer supported if I understand the following blog correctly: https://blog.readthedocs.com/github-git-protocol-deprecation/

**Comment by int-e** [comment]
Sorry, I had missed the point of that change. Thanks for pointing that out!
